// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwVojOiN7S1BG5aBPGW1NqzODmDJ3WfrE',
    appId: '1:124944787451:web:d053feb373198c63be4d5e',
    messagingSenderId: '124944787451',
    projectId: 'we-chat-34540',
    authDomain: 'we-chat-34540.firebaseapp.com',
    storageBucket: 'we-chat-34540.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvlZ_oqdCaDhSHSQZPgiCp_0QjGSWi0qE',
    appId: '1:124944787451:android:69fc0db24ebff0bbbe4d5e',
    messagingSenderId: '124944787451',
    projectId: 'we-chat-34540',
    storageBucket: 'we-chat-34540.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjFq97fMb3XCKEeBgXbdfSy9SdSo0VAJY',
    appId: '1:124944787451:ios:6b2124db9d0f06dabe4d5e',
    messagingSenderId: '124944787451',
    projectId: 'we-chat-34540',
    storageBucket: 'we-chat-34540.appspot.com',
    iosBundleId: 'com.example.weChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjFq97fMb3XCKEeBgXbdfSy9SdSo0VAJY',
    appId: '1:124944787451:ios:720dab8b03beb4b3be4d5e',
    messagingSenderId: '124944787451',
    projectId: 'we-chat-34540',
    storageBucket: 'we-chat-34540.appspot.com',
    iosBundleId: 'com.example.weChat.RunnerTests',
  );
}
